# Generated by Django 4.1 on 2022-10-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_type_of_c_postroom_host_message_postroom_type_of_c'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postroom',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='postroom',
            name='post_pic',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
