# Generated by Django 4.1 on 2022-11-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_postroom_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postroom',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
