# Generated by Django 4.1 on 2022-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_postroom_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postroom',
            name='level',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
