# Generated by Django 4.1 on 2022-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_message_options_remove_postroom_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postroom',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
