# Generated by Django 4.1 on 2022-12-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_message_options_profile_of_u'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_of_u',
        ),
    ]
